### ISSUE TITLE
Could not fill variables in: (undefined) undefined

### ISSUE THREAD

**Issue by dijs** [dijs/infobox-parser#8]
That happens when I search for "Wayne Rooney" using https://de.wikipedia.org/w/api.php 

Doesn't happen with the English Wikipedia version.

```
Error: Something went wrong. Could not fill variables in: (undefined) undefined
    at fillVariables (/app/node_modules/infobox-parser/build/bundle.min.js:1:1957)
    at fillVariablesUntilDone (/app/node_modules/infobox-parser/build/bundle.min.js:1:2659)
    at fillVariablesUntilDone (/app/node_modules/infobox-parser/build/bundle.min.js:1:2695)
    at getVariableValue (/app/node_modules/infobox-parser/build/bundle.min.js:1:3339)
    at reduceVariable (/app/node_modules/infobox-parser/build/bundle.min.js:1:3755)
    at /app/node_modules/infobox-parser/build/bundle.min.js:1:3935
    at Array.reduce (native)
    at extractProperties (/app/node_modules/infobox-parser/build/bundle.min.js:1:4114)
    at index (/app/node_modules/infobox-parser/build/bundle.min.js:1:9971)
    at /app/node_modules/wikijs/dist/page.js:1:1579
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by dijs** [comment]
Source https://github.com/dijs/wiki/issues/52
